package net.dinkla.nkp.report

private const val INSTABILITY_LOW = 0.3
private const val INSTABILITY_HIGH = 0.7

private fun instabilityColorClass(instability: Double): String =
    when {
        instability < INSTABILITY_LOW -> "instability-low"
        instability > INSTABILITY_HIGH -> "instability-high"
        else -> "instability-medium"
    }

/**
 * Generates a standalone HTML report with embedded CSS, JavaScript, and Mermaid diagrams.
 */
class HtmlReportGenerator(
    private val data: ReportData,
    private val options: ReportOptions,
) {
    fun generate(): String =
        buildString {
            appendLine("<!DOCTYPE html>")
            appendLine("<html lang=\"en\">")
            appendHead()
            appendLine("<body>")
            appendNavigation()
            appendLine("<main class=\"container\">")
            appendOverviewSection()
            appendPackagesSection()
            appendClassesSection()
            appendFilesSection()
            appendCouplingSection()
            appendCircularDependenciesSection()
            appendDiagramsSection()
            appendLine("</main>")
            appendLine("<footer class=\"footer\">")
            appendLine("<p>Generated by kotlin-nkp on ${formatTimestamp(System.currentTimeMillis())}</p>")
            appendLine("</footer>")
            appendLine("<script src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>")
            appendLine("<script>")
            appendLine(JS_SCRIPTS)
            appendLine("</script>")
            appendLine("</body>")
            appendLine("</html>")
        }

    private fun StringBuilder.appendHead() {
        appendLine("<head>")
        appendLine("<meta charset=\"UTF-8\">")
        appendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
        appendLine("<title>${escapeHtml(options.title)}</title>")
        appendLine("<style>")
        appendLine(CSS_STYLES)
        appendLine("</style>")
        appendLine("</head>")
    }

    private fun StringBuilder.appendNavigation() {
        appendLine("<nav class=\"navbar\">")
        appendLine("<div class=\"nav-brand\">${escapeHtml(options.title)}</div>")
        appendLine("<ul class=\"nav-links\">")
        appendLine("<li><a href=\"#overview\">Overview</a></li>")
        appendLine("<li><a href=\"#packages\">Packages</a></li>")
        appendLine("<li><a href=\"#classes\">Classes</a></li>")
        appendLine("<li><a href=\"#files\">Files</a></li>")
        appendLine("<li><a href=\"#coupling\">Coupling</a></li>")
        appendLine("<li><a href=\"#circular-deps\">Circular Deps</a></li>")
        appendLine("<li><a href=\"#diagrams\">Diagrams</a></li>")
        appendLine("</ul>")
        appendLine("</nav>")
    }

    private fun StringBuilder.appendOverviewSection() {
        appendLine("<section id=\"overview\" class=\"section\">")
        appendLine("<h2>Overview</h2>")
        appendLine("<div class=\"overview-grid\">")
        listOf(
            Triple("Files", formatNumber(data.totalFiles), "file-icon"),
            Triple("Packages", formatNumber(data.totalPackages), "package-icon"),
            Triple("Classes", formatNumber(data.totalClasses), "class-icon"),
            Triple("Functions", formatNumber(data.totalFunctions), "function-icon"),
            Triple("Properties", formatNumber(data.totalProperties), "property-icon"),
        ).forEach { (label, value, iconClass) ->
            appendLine("<div class=\"metric-card\">")
            appendLine("<div class=\"metric-icon $iconClass\"></div>")
            appendLine("<div class=\"metric-value\">$value</div>")
            appendLine("<div class=\"metric-label\">$label</div>")
            appendLine("</div>")
        }
        appendLine("</div>")

        appendLine("<div class=\"health-card ${data.healthScore.overallStatus.cssClass}\">")
        appendLine("<h3>Project Health: ${data.healthScore.overallStatus.label}</h3>")
        appendLine("<ul>")
        if (data.healthScore.hasCircularDependencies) {
            val count = data.healthScore.circularDependencyCount
            appendLine("<li>Circular dependencies detected: $count cycle(s)</li>")
        } else {
            appendLine("<li>No circular dependencies detected</li>")
        }
        appendLine("<li>Average instability: ${formatDouble(data.healthScore.averageInstability)}</li>")
        if (data.healthScore.highInstabilityPackages > 0) {
            appendLine("<li>High instability packages: ${data.healthScore.highInstabilityPackages}</li>")
        }
        appendLine("</ul>")
        appendLine("</div>")

        appendLine("<div class=\"info-card\">")
        appendLine("<h3>Project Information</h3>")
        appendLine("<table class=\"info-table\">")
        appendLine("<tr><td>Directory</td><td>${escapeHtml(data.project.directory)}</td></tr>")
        appendLine("<tr><td>Parsed</td><td>${formatTimestamp(data.project.parseTimestamp)}</td></tr>")
        appendLine("</table>")
        appendLine("</div>")
        appendLine("</section>")
    }

    private fun StringBuilder.appendPackagesSection() {
        appendLine("<section id=\"packages\" class=\"section\">")
        appendLine("<h2>Packages</h2>")
        appendLine("<div class=\"filter-bar\">")
        appendLine("<input type=\"text\" id=\"package-filter\" placeholder=\"Filter...\" class=\"filter-input\">")
        appendLine("</div>")
        appendLine("<div class=\"table-container\">")
        appendLine("<table class=\"data-table sortable\" id=\"packages-table\">")
        appendLine("<thead><tr>")
        appendLine("<th data-sort=\"string\">Package</th>")
        appendLine("<th data-sort=\"number\">Files</th>")
        appendLine("<th data-sort=\"number\">Classes</th>")
        appendLine("<th data-sort=\"number\">Functions</th>")
        appendLine("<th data-sort=\"number\">Properties</th>")
        appendLine("<th data-sort=\"number\">Imports</th>")
        appendLine("</tr></thead>")
        appendLine("<tbody>")
        data.packageStatistics.forEach { pkg ->
            val decl = pkg.declarationStatistics
            val imports = pkg.importStatistics
            appendLine("<tr data-filter=\"${escapeHtml(pkg.packageName.name.lowercase())}\">")
            appendLine("<td>${escapeHtml(pkg.packageName.name)}</td>")
            appendLine("<td>${decl.files}</td><td>${decl.classes}</td>")
            appendLine("<td>${decl.functions}</td><td>${decl.properties}</td>")
            appendLine("<td>${imports.total}</td></tr>")
        }
        appendLine("</tbody></table></div></section>")
    }

    private fun StringBuilder.appendClassesSection() {
        appendLine("<section id=\"classes\" class=\"section\">")
        appendLine("<h2>Classes</h2>")
        appendLine("<div class=\"filter-bar\">")
        appendLine("<input type=\"text\" id=\"class-filter\" placeholder=\"Filter...\" class=\"filter-input\">")
        appendLine("</div>")
        appendLine("<div class=\"table-container\">")
        appendLine("<table class=\"data-table sortable\" id=\"classes-table\">")
        appendLine("<thead><tr>")
        appendLine("<th data-sort=\"string\">Class</th>")
        appendLine("<th data-sort=\"string\">Package</th>")
        appendLine("<th data-sort=\"string\">Type</th>")
        appendLine("<th data-sort=\"number\">Functions</th>")
        appendLine("<th data-sort=\"number\">Properties</th>")
        appendLine("<th data-sort=\"number\">Superclasses</th>")
        appendLine("<th data-sort=\"number\">Subclasses</th>")
        appendLine("</tr></thead>")
        appendLine("<tbody>")
        data.classStatistics.forEach { cls ->
            val filterKey = "${cls.className} ${cls.packageName.name}".lowercase()
            appendLine("<tr data-filter=\"${escapeHtml(filterKey)}\">")
            appendLine("<td>${escapeHtml(cls.className)}</td>")
            appendLine("<td>${escapeHtml(cls.packageName.name)}</td>")
            appendLine("<td>${cls.elementType.name.lowercase()}</td>")
            appendLine("<td>${cls.metrics.functions}</td><td>${cls.metrics.properties}</td>")
            appendLine("<td>${cls.metrics.superClasses}</td><td>${cls.metrics.subClasses}</td></tr>")
        }
        appendLine("</tbody></table></div></section>")
    }

    private fun StringBuilder.appendFilesSection() {
        appendLine("<section id=\"files\" class=\"section\">")
        appendLine("<h2>Files</h2>")
        appendLine("<div class=\"filter-bar\">")
        appendLine("<input type=\"text\" id=\"file-filter\" placeholder=\"Filter...\" class=\"filter-input\">")
        appendLine("</div>")
        appendLine("<div class=\"table-container\">")
        appendLine("<table class=\"data-table sortable\" id=\"files-table\">")
        appendLine("<thead><tr>")
        appendLine("<th data-sort=\"string\">File</th>")
        appendLine("<th data-sort=\"number\">Imports</th>")
        appendLine("<th data-sort=\"number\">Declarations</th>")
        appendLine("<th data-sort=\"number\">Classes</th>")
        appendLine("<th data-sort=\"number\">Functions</th>")
        appendLine("<th data-sort=\"number\">Instability</th>")
        appendLine("</tr></thead>")
        appendLine("<tbody>")
        data.fileStatistics.forEach { file ->
            val relativePath = data.project.relativePath(file.filePath.path)
            val colorClass = instabilityColorClass(file.coupling.instability)
            appendLine("<tr data-filter=\"${escapeHtml(relativePath.lowercase())}\">")
            appendLine("<td title=\"${escapeHtml(file.filePath.path)}\">${escapeHtml(relativePath)}</td>")
            appendLine("<td>${file.metrics.imports}</td><td>${file.metrics.declarations}</td>")
            appendLine("<td>${file.metrics.classes}</td><td>${file.metrics.functions}</td>")
            appendLine("<td class=\"$colorClass\">${formatDouble(file.coupling.instability)}</td></tr>")
        }
        appendLine("</tbody></table></div></section>")
    }

    private fun StringBuilder.appendCouplingSection() {
        appendLine("<section id=\"coupling\" class=\"section\">")
        appendLine("<h2>Package Coupling</h2>")
        appendLine("<p class=\"section-description\">")
        appendLine("Ca = Afferent Coupling (incoming), Ce = Efferent Coupling (outgoing), ")
        appendLine("I = Instability (Ce / (Ca + Ce))</p>")
        appendLine("<div class=\"table-container\">")
        appendLine("<table class=\"data-table sortable\" id=\"coupling-table\">")
        appendLine("<thead><tr>")
        appendLine("<th data-sort=\"string\">Package</th>")
        appendLine("<th data-sort=\"number\">Ca</th>")
        appendLine("<th data-sort=\"number\">Ce</th>")
        appendLine("<th data-sort=\"number\">Instability</th>")
        appendLine("</tr></thead>")
        appendLine("<tbody>")
        data.couplingData.forEach { item ->
            val colorClass = instabilityColorClass(item.coupling.instability)
            appendLine("<tr>")
            appendLine("<td>${escapeHtml(item.packageName.name)}</td>")
            appendLine("<td>${item.coupling.afferentCoupling}</td>")
            appendLine("<td>${item.coupling.efferentCoupling}</td>")
            appendLine("<td class=\"$colorClass\">${formatDouble(item.coupling.instability)}</td></tr>")
        }
        appendLine("</tbody></table></div></section>")
    }

    private fun StringBuilder.appendCircularDependenciesSection() {
        appendLine("<section id=\"circular-deps\" class=\"section\">")
        appendLine("<h2>Circular Dependencies</h2>")
        if (data.circularDependencies.hasCycles) {
            val cycles = data.circularDependencies
            appendLine("<div class=\"alert alert-warning\">")
            appendLine("<strong>Warning:</strong> ${cycles.totalCycles} circular dependency cycle(s) ")
            appendLine("detected involving ${cycles.packagesInCycles.size} package(s).</div>")
            appendLine("<div class=\"cycles-list\">")
            cycles.cycles.forEachIndexed { index, cycle ->
                appendLine("<div class=\"cycle-card\">")
                appendLine("<h4>Cycle ${index + 1} (${cycle.size} packages)</h4>")
                appendLine("<ul class=\"cycle-packages\">")
                cycle.packages.forEach { pkg -> appendLine("<li>${escapeHtml(pkg.name)}</li>") }
                appendLine("</ul></div>")
            }
            appendLine("</div>")
        } else {
            appendLine("<div class=\"alert alert-success\">")
            appendLine("<strong>No circular dependencies detected.</strong> Package structure is clean.</div>")
        }
        appendLine("</section>")
    }

    private fun StringBuilder.appendDiagramsSection() {
        appendLine("<section id=\"diagrams\" class=\"section\">")
        appendLine("<h2>Diagrams</h2>")
        appendLine("<div class=\"diagram-tabs\">")
        appendLine("<button class=\"tab-btn active\" data-diagram=\"class-diagram\">Class Diagram</button>")
        appendLine("<button class=\"tab-btn\" data-diagram=\"import-diagram\">Import Flow</button>")
        appendLine("<button class=\"tab-btn\" data-diagram=\"coupling-diagram\">Coupling</button>")
        appendLine("</div>")
        listOf(
            Triple("class-diagram", data.mermaidClassDiagram, true),
            Triple("import-diagram", data.mermaidImportDiagram, false),
            Triple("coupling-diagram", data.mermaidCouplingDiagram, false),
        ).forEach { (id, diagram, isActive) ->
            val activeClass = if (isActive) " active" else ""
            appendLine("<div id=\"$id\" class=\"diagram-container$activeClass\">")
            appendLine("<pre class=\"mermaid\">${escapeHtml(diagram)}</pre></div>")
        }
        appendLine("</section>")
    }

    companion object {
        private val CSS_STYLES =
            """
            :root {
                --primary: #2563eb;
                --primary-dark: #1d4ed8;
                --success: #16a34a;
                --warning: #ca8a04;
                --danger: #dc2626;
                --bg: #f8fafc;
                --card-bg: #ffffff;
                --text: #1e293b;
                --text-muted: #64748b;
                --border: #e2e8f0;
            }
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                background: var(--bg);
                color: var(--text);
                line-height: 1.6;
            }
            .navbar {
                background: var(--card-bg);
                border-bottom: 1px solid var(--border);
                padding: 1rem 2rem;
                position: sticky;
                top: 0;
                z-index: 100;
                display: flex;
                justify-content: space-between;
                align-items: center;
            }
            .nav-brand { font-weight: 600; font-size: 1.25rem; color: var(--primary); }
            .nav-links { list-style: none; display: flex; gap: 1.5rem; }
            .nav-links a { text-decoration: none; color: var(--text-muted); transition: color 0.2s; }
            .nav-links a:hover { color: var(--primary); }
            .container { max-width: 1400px; margin: 0 auto; padding: 2rem; }
            .section { background: var(--card-bg); border-radius: 8px; padding: 1.5rem; margin-bottom: 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            .section h2 { margin-bottom: 1rem; color: var(--primary); border-bottom: 2px solid var(--primary); padding-bottom: 0.5rem; }
            .section-description { color: var(--text-muted); margin-bottom: 1rem; font-size: 0.9rem; }
            .overview-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
            .metric-card {
                background: linear-gradient(135deg, var(--primary), var(--primary-dark));
                color: white;
                padding: 1.25rem;
                border-radius: 8px;
                text-align: center;
            }
            .metric-value { font-size: 2rem; font-weight: 700; }
            .metric-label { font-size: 0.875rem; opacity: 0.9; }
            .health-card { padding: 1rem; border-radius: 8px; margin-bottom: 1rem; }
            .health-good { background: #dcfce7; border-left: 4px solid var(--success); }
            .health-caution { background: #fef9c3; border-left: 4px solid var(--warning); }
            .health-warning { background: #fee2e2; border-left: 4px solid var(--danger); }
            .health-card h3 { margin-bottom: 0.5rem; }
            .health-card ul { margin-left: 1.5rem; }
            .info-card { padding: 1rem; background: var(--bg); border-radius: 8px; }
            .info-card h3 { margin-bottom: 0.5rem; }
            .info-table { width: 100%; }
            .info-table td { padding: 0.25rem 0; }
            .info-table td:first-child { font-weight: 500; width: 120px; }
            .filter-bar { margin-bottom: 1rem; }
            .filter-input {
                width: 100%;
                max-width: 300px;
                padding: 0.5rem 1rem;
                border: 1px solid var(--border);
                border-radius: 4px;
                font-size: 0.9rem;
            }
            .filter-input:focus { outline: none; border-color: var(--primary); }
            .table-container { overflow-x: auto; }
            .data-table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
            .data-table th, .data-table td { padding: 0.75rem; text-align: left; border-bottom: 1px solid var(--border); }
            .data-table th { background: var(--bg); font-weight: 600; cursor: pointer; user-select: none; }
            .data-table th:hover { background: var(--border); }
            .data-table th::after { content: ' \2195'; opacity: 0.3; }
            .data-table th.sort-asc::after { content: ' \2191'; opacity: 1; }
            .data-table th.sort-desc::after { content: ' \2193'; opacity: 1; }
            .data-table tbody tr:hover { background: var(--bg); }
            .instability-low { color: var(--success); font-weight: 500; }
            .instability-medium { color: var(--warning); font-weight: 500; }
            .instability-high { color: var(--danger); font-weight: 500; }
            .alert { padding: 1rem; border-radius: 8px; margin-bottom: 1rem; }
            .alert-success { background: #dcfce7; color: #166534; }
            .alert-warning { background: #fee2e2; color: #991b1b; }
            .cycles-list { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; }
            .cycle-card { background: var(--bg); padding: 1rem; border-radius: 8px; border-left: 3px solid var(--danger); }
            .cycle-card h4 { margin-bottom: 0.5rem; color: var(--danger); }
            .cycle-packages { margin-left: 1.25rem; }
            .diagram-tabs { display: flex; gap: 0.5rem; margin-bottom: 1rem; flex-wrap: wrap; }
            .tab-btn {
                padding: 0.5rem 1rem;
                border: 1px solid var(--border);
                background: var(--card-bg);
                border-radius: 4px;
                cursor: pointer;
                font-size: 0.9rem;
                transition: all 0.2s;
            }
            .tab-btn:hover { background: var(--bg); }
            .tab-btn.active { background: var(--primary); color: white; border-color: var(--primary); }
            .diagram-container { display: none; overflow-x: auto; }
            .diagram-container.active { display: block; }
            .mermaid { background: var(--bg); padding: 1rem; border-radius: 8px; }
            .footer { text-align: center; padding: 2rem; color: var(--text-muted); font-size: 0.875rem; }
            @media (max-width: 768px) {
                .navbar { flex-direction: column; gap: 1rem; }
                .nav-links { flex-wrap: wrap; justify-content: center; }
                .container { padding: 1rem; }
            }
            """.trimIndent()

        private val JS_SCRIPTS =
            """
            // Initialize Mermaid
            mermaid.initialize({ startOnLoad: true, theme: 'default' });

            // Table sorting
            document.querySelectorAll('.sortable').forEach(table => {
                const headers = table.querySelectorAll('th[data-sort]');
                headers.forEach((header, index) => {
                    header.addEventListener('click', () => {
                        const tbody = table.querySelector('tbody');
                        const rows = Array.from(tbody.querySelectorAll('tr'));
                        const sortType = header.dataset.sort;
                        const isAsc = header.classList.contains('sort-asc');

                        headers.forEach(h => h.classList.remove('sort-asc', 'sort-desc'));
                        header.classList.add(isAsc ? 'sort-desc' : 'sort-asc');

                        rows.sort((a, b) => {
                            const aVal = a.cells[index].textContent.trim();
                            const bVal = b.cells[index].textContent.trim();
                            if (sortType === 'number') {
                                return (isAsc ? -1 : 1) * (parseFloat(aVal) - parseFloat(bVal));
                            }
                            return (isAsc ? -1 : 1) * aVal.localeCompare(bVal);
                        });

                        rows.forEach(row => tbody.appendChild(row));
                    });
                });
            });

            // Filtering
            document.querySelectorAll('.filter-input').forEach(input => {
                input.addEventListener('input', (e) => {
                    const filter = e.target.value.toLowerCase();
                    const tableId = e.target.id.replace('-filter', 's-table');
                    const table = document.getElementById(tableId);
                    if (!table) return;

                    table.querySelectorAll('tbody tr').forEach(row => {
                        const text = row.dataset.filter || row.textContent.toLowerCase();
                        row.style.display = text.includes(filter) ? '' : 'none';
                    });
                });
            });

            // Diagram tabs
            document.querySelectorAll('.tab-btn').forEach(btn => {
                btn.addEventListener('click', () => {
                    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
                    document.querySelectorAll('.diagram-container').forEach(d => d.classList.remove('active'));
                    btn.classList.add('active');
                    document.getElementById(btn.dataset.diagram).classList.add('active');
                    mermaid.init(undefined, document.querySelectorAll('.mermaid'));
                });
            });
            """.trimIndent()
    }
}
